# Generated by Django 5.1.3 on 2024-11-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitaciones', '0002_licitacion_presupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.TextField()),
                ('prioridad', models.CharField(max_length=50)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdrs', to='licitaciones.licitacion')),
            ],
        ),
    ]
